version: "3.6"
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    networks:
      - todo-net
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: soymavc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: guest
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - todo-net
  mailer:
    image: maildev/maildev:latest
    restart: always
    ports:
      - "1080:1080"
      - "1025:1025"
volumes:
  db_data:
  pgadmin-data:
networks:
  todo-net:
    name: todo-net
