version: "3.6"
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    networks:
      - todo-net
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${USER_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${USER_PASSWORD}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - todo-net
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data
volumes:
  db_data:
  pgadmin-data:
networks:
  todo-net:
    name: todo-net
